### ISSUE TITLE
It stopped working

### ISSUE THREAD

**Issue by cabello** [marclipovsky/vscode-string-manipulation#10]
Hi 👋 

I tried executing string manipulation like in the demo gif and it does not work anymore.

MacOS - Code Version 1.27.2 (1.27.2)

I tried looking for debugging output in Output and selecting different Log options in the drop-down but I did not see any error.

Not sure what else I can provide to help debugging it.

**Comment by marclipovsky** [comment]
This may be related to #9. I am on vacation and will investigate as soon as I am able.

**Comment by marclipovsky** [comment]
Resolved with #13
