### ISSUE TITLE
Include Increment/Decrements Feature 

### ISSUE THREAD

**Issue by mesadhan** [marclipovsky/vscode-string-manipulation#11]
Increment/Decrement feature is really helpful, I use this tool a long time in JetBrains IDE 

- [ ] 1. Decrement
- [ ] 2. Increment
- [ ] 3. Duplicate & Decrement
- [ ] 5. Increment Duplicates
- [ ] 4. Create Sequence

**Comment by marclipovsky** [comment]
Can you provide examples of each of the features listed? I'll take a look and see if they make sense to include into this extension.

**Comment by mesadhan** [comment]
1. From the selected string, **Increment/decrement** all numbers found.
2. From the selected string, Duplicate line and **increment/decrement** all numbers found.
3. **Create sequence** - Keep the first number, replace all other by incrementing
4. The selected text will be **Increment duplicate** numbers

**I'm talking about this plugin:-**
- https://plugins.jetbrains.com/plugin/2162-string-manipulation

**Comment by marclipovsky** [comment]
@mesadhan Can you provide a before and after of 3 and 4?
