### ISSUE TITLE
Add option to titleize an article headline using style guides

### ISSUE THREAD

**Issue by nickjj** [marclipovsky/vscode-string-manipulation#2]
Thoughts on adding a new option that uses well defined style guides to properly titleize a headline?

For instance, check out this website http://titlecapitalization.com/.

The Chicago Manual of style (along with the NY Times style guide) are both well defined style guides on how to capitalize certain words in a headline.

A plugin exists for Sublime Text that follows a similar style guide at https://github.com/mattstevens/sublime-titlecase.

**Use case:**

When writing blog posts it's nice to be able to highlight a title and then "titleize" it without having to visit the titleize website I linked earlier.

**Comment by nickjj** [comment]
Thanks, can you publish this so it's available in VSCode as an update?

**Comment by nickjj** [comment]
Thanks. Is there a timeline to when this will be an available option to pick in VSCode?

**Comment by marclipovsky** [comment]
Yes probably this evening.
