### ISSUE TITLE
I hope to add an option to switch between the specified two types

### ISSUE THREAD

**Issue by zsedcbm** [marclipovsky/vscode-string-manipulation#24]
I hope to add an option to switch between the specified two types, so that I can quickly toggle through the shortcut keys

**Comment by prankymat** [comment]
indeed I'd like to quickly toggle between all the types actually

**Comment by zsedcbm** [comment]
Sorry for not being clear. If I have ten words, the original word is in camelize format, and I want to convert it to capitalize format. Now I have to call up the command window and select capitalize format when operating. Can you provide a shortcut key to quickly use the last converted format?

**Comment by prankymat** [comment]
I have made a PR #33 which adds a context menu and the repeat last action shortcut.

**Comment by prankymat** [comment]
<img width="1448" alt="CleanShot 2022-03-13 at 17 15 06@2x" src="https://user-images.githubusercontent.com/2998111/158052965-83d826dd-e059-4121-84fc-ca1f2fa2d537.png">

You can define a shortcut with the repeat last action command
