### ISSUE TITLE
duplicate and increment all numbers

### ISSUE THREAD

**Issue by MohammadMD1383** [marclipovsky/vscode-string-manipulation#28]
I think it doesn't work correctly.
if you look at [this plugin for intelliJ based IDEs](https://plugins.jetbrains.com/plugin/2162-string-manipulation), it increments all duplicate numbers in current selection.

for example:
```
var1
var1
var1
var1
```

then after selecting all of them and doing the action it should change like this:
```
var1
var2
var3
var4
```

**Comment by marclipovsky** [comment]
Is it a multi selection or single selection of multiple lines?

**Comment by MohammadMD1383** [comment]
https://user-images.githubusercontent.com/69088224/121667009-1a13c680-cabf-11eb-980b-46e2cd9f0c10.mp4

please see this.

**Comment by marclipovsky** [comment]
Very helpful. Thanks I'll look into this.

**Comment by marclipovsky** [comment]
Re-read your initial comment and this is actually working as intended. What you are wanting to use is the "Sequence all numbers" action instead of the duplicate and increment action.
