### ISSUE TITLE
Potential issues with Chicago Style titles

### ISSUE THREAD

**Issue by nickjj** [marclipovsky/vscode-string-manipulation#3]
I just spot checked about 25 titles and 23 of them matched http://titlecapitalization.com.

The 2 that failed involved the words "how" and "along", used in the context of:

---

**Your plugin**: A Crash Course on how Radars Work
**http://titlecapitalization.com/**: A Crash Course on How Radars Work

"how" probably should be in caps.

---

**Your plugin**: Follow Along with Me
**http://titlecapitalization.com/**: Follow along with Me

I have to wonder if http://titlecapitalization.com/ is wrong here with "along" because I always end up manually fixing that word on my own later because there's no reason why "along" shouldn't be capitalized.

Edit: For reference I'm not a professional editor (that's why I depend on tools like this :)). Just going by "feel".

**Comment by marclipovsky** [comment]
@nickjj You'd have to take that up with https://github.com/timdp/chicago-capitalize
