### ISSUE TITLE
Can't run multiple commands sequentially

### ISSUE THREAD

**Issue by rdw4nau** [marclipovsky/vscode-string-manipulation#37]
In trying to automate multiple commands that work disparately, am unable to successfully run multiple commands via a chained extension. Only the first command of any sequence runs on selected text (in this case, decapitalize).

Have tried with multiple extensions:

macros:
https://marketplace.visualstudio.com/items?itemName=geddski.macros

```
    "macros": {
        "reverseTheName": [
            "string-manipulation.decapitalize",
            "string-manipulation.reverse",
            "string-manipulation.capitalize"
        ]
    }
```

multi-command:
https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command

```
    "multiCommand.commands": [
        {
            "command": "multiCommand.reverseName",
            "interval": 1,
            "sequence": [
                "string-manipulation.decapitalize",
                "string-manipulation.reverse",
                "string-manipulation.capitalize"
            ]
        }
    ]
```

**Comment by rdw4nau** [comment]
Resolved by adding a focus back to the editor (worked with multiCommand, but not macros)
`    "multiCommand.commands": [
        {
            "command": "multiCommand.reverseName",
            "sequence": [
                "string-manipulation.decapitalize",
                "workbench.action.focusActiveEditorGroup",
                "string-manipulation.reverse",
                "workbench.action.focusActiveEditorGroup",
                "string-manipulation.capitalize"
            ]
        }
    ]`

**Comment by marclipovsky** [comment]
@rdw4nau Was this working before yesterday? Or is this something you just setup?

It seems like you should be able to run it how you initially had it configured. I may still investigate this.

**Comment by rdw4nau** [comment]
@marclipovsky I am new to this extension, so it's something I just setup.
