### ISSUE TITLE
Consider title'izing the current line if nothing is selected

### ISSUE THREAD

**Issue by nickjj** [marclipovsky/vscode-string-manipulation#4]
**Use case**:

You are writing a blog post written in markdown and all of your titles are on their own line, but now you want to titleize them using the Chicago Manual of Style.

In Sublime 3 (it has a similar plugin as yours), all I had to do was move the cursor to the line I wanted to modify and hit a hotkey. With your plugin I need to take the extra step of selecting the text.

95% of the time if I want to title'ize a header, it's the entire line. I think this is pretty common, so maybe the default action could be to title'ize the current line if nothing is selected.

It's one of those things where once you don't have it, you really miss it.

**Comment by marclipovsky** [comment]
I'm sorry but this plugin is intended for non-literary use. Feel free to fork the project or create a pull request.

**Comment by nickjj** [comment]
This is quite useful outside of literary use, but hey it's your extension. :)

**Comment by marclipovsky** [comment]
@nickjj I'd be happy to clone this extension to create one for writing use. Can you give me more examples for other title styles? Then I'll move the two that I added already to that extension.

**Comment by nickjj** [comment]
I think the 2 mentioned in the previous issue are enough to cover the 95%. It's all I've ever seen used by other authors.

Really just applying any title style to the current line if the selection is none would be enough to not need a second extension (unless you wanted to pull them out regardless).
