### ISSUE TITLE
Uppercase, lowercase option

### ISSUE THREAD

**Issue by Dennis-Ciocca-Solis2** [marclipovsky/vscode-string-manipulation#46]
Is it me or there is no options to change all letters to Uppercase or Lowercase?

**Comment by marclipovsky** [comment]
I believe this is built into VSCode, the commands are prefixed with ’Transform:’. Let me know if it doesn't appear for you.

**Comment by marclipovsky** [comment]
I believe this is built into VSCode, the commands are prefixed with ’Transform:’. Let me know if it doesn't appear for you.

**Comment by marclipovsky** [comment]
Closing this out.
