### ISSUE TITLE
Multilineselection does not count as one Selection

### ISSUE THREAD

**Issue by h-brockmann** [marclipovsky/vscode-string-manipulation#47]
![grafik](https://github.com/marclipovsky/vscode-string-manipulation/assets/2248202/a25427ec-8bb5-46a8-baa2-d8c137c43232)
![grafik](https://github.com/marclipovsky/vscode-string-manipulation/assets/2248202/fb3bb170-c317-4047-abf5-791aacf0063b)

The selection over parts of multiple lines does not count as single selection to use with "Sequence all numbers".
Would be a great update that would make this part really helpful.

Now I have to cut the selection, paste it in another document, increment the numbers and repaste it back into the original.

I would greatly appreciate the update.

**Comment by marclipovsky** [comment]
Thanks for catching this. I'll take a look this weekend.

**Comment by joshf26** [comment]
Hi, I also ran into issues with this. I took a stab at it here: https://github.com/marclipovsky/vscode-string-manipulation/pull/50

**Comment by marclipovsky** [comment]
Sounds good, I'll take a look at this today.

**Comment by marclipovsky** [comment]
Published to marketplace.
