### ISSUE TITLE
Ability to uppercase and lowercase a string

### ISSUE THREAD

**Issue by jlindenbaum** [marclipovsky/vscode-string-manipulation#5]
It'd be great if this extension could take a highlighted string and make it "UPPERCASE" and "lowercase".

**Comment by marclipovsky** [comment]
This comes built-in with VS Code. Pull up your command pallet and type 'uppercase' or 'lowercase'.

![screen shot 2017-08-05 at 9 47 54 pm](https://user-images.githubusercontent.com/112484/29000689-ef9e7878-7a27-11e7-9862-9f0043894281.png)

![screen shot 2017-08-05 at 9 47 45 pm](https://user-images.githubusercontent.com/112484/29000683-c61a4950-7a27-11e7-85f2-f1a95028d4aa.png)
