### ISSUE TITLE
v0.7.2 doesn't work at all

### ISSUE THREAD

**Issue by pewscorner** [marclipovsky/vscode-string-manipulation#53]
The latest update from v0.6.1 to v0.7.2 seems to have broken all functionality. All String Manipulation functions now pop up an error saying that the function doesn't exist.

<img width="266" alt="image" src="https://github.com/user-attachments/assets/69b2f815-ba46-4a25-8551-8b45bc4c4fd1">

String Manipulation v0.7.2
VS Code 1.93.1
Windows 11

**Comment by marclipovsky** [comment]
Ugh that's annoying. Ok please use version 0.6.1 for now. I'll resolve 0.7
today.

**Comment by marclipovsky** [comment]
Should be all set with 0.7.5. Thanks for flagging.
