### ISSUE TITLE
Title Case function deletes punctuation, breaks words

### ISSUE THREAD

**Issue by Down10** [marclipovsky/vscode-string-manipulation#8]
When using Title Case on a string, the result is, well, wrong. The transformation over the string removes punctuation instead of ignoring it. This results in the following junk:

Original string: `FERRIS BEULLER'S DAY OFF (1986)`

Expected Result: `Ferris Beuller's Day Off (1986)`

Actual Result: `Ferris Beuller S Day Off 1986`

Hope this can be fixed soon!

**Comment by marclipovsky** [comment]
I was not able to reproduce this. 

![title-case-test](https://user-images.githubusercontent.com/112484/39796004-e27e0c2a-5308-11e8-85a1-f1598436f7d3.gif)
